import java.util.*;

class Student {
    private String id, name;
    private int marks;

    public Student(String id, String name, int marks) {
        this.id = id;
        this.name = name;
        this.marks = marks;
    }

    public String getId() { return id; }
    public String getName() { return name; }
    public int getMarks() { return marks; }

    public String getRole() { return "Undergrad"; }

    @Override
    public String toString() {
        return id + " " + name + " (" + marks + ") " + getRole();
    }
}

class GraduateStudent extends Student {
    private String area;

    public GraduateStudent(String id, String name, int marks, String area) {
        super(id, name, marks);
        this.area = area;
    }

    @Override
    public String getRole() {
        return "Grad(" + area + ")";
    }
}

class Repository<T> {
    private Map<String, T> data = new HashMap<>();
    public void save(String id, T obj) { data.put(id, obj); }
    public T find(String id) { return data.get(id); }
    public void delete(String id) { data.remove(id); }
}

class Teacher {
    protected String teacherId;
    protected String name;

    public Teacher(String teacherId, String name) {
        this.teacherId = teacherId;
        this.name = name;
    }

    public String getRole() {
        return "Teacher";
    }
}

class SubjectTeacher extends Teacher {
    private String subject;

    public SubjectTeacher(String teacherId, String name, String subject) {
        super(teacherId, name);
        this.subject = subject;
    }

    public String getRole() {
        return "Subject Teacher (" + subject + ")";
    }

    public void generateReport(List<Student> students) {
        System.out.println("\nReport for subject: " + subject);
        System.out.println("Generated by: " + name + " (" + teacherId + ")\n");
        System.out.println("ID\tNAME\tMARKS");
        for (Student s : students) {
            System.out.println(s.getId() + "\t" + s.getName() + "\t" + s.getMarks());
        }
    }
}

public class Main {
    public static void main(String[] args) {
        List<Student> list = new ArrayList<>();
        list.add(new Student("s1", "Advitiya", 90));
        list.add(new Student("s2", "Jayesh", 85));
        list.add(new Student("s3", "Priya", 78));
        list.add(new GraduateStudent("G1", "Ananya", 92, "CS"));

        Repository<Student> repo = new Repository<>();
        for (Student s : list) repo.save(s.getId(), s);

        System.out.println("ALL STUDENTS:");
        list.forEach(System.out::println);

        Iterator<Student> it = list.iterator();
        while(it.hasNext()){
            Student st = it.next();
            if(st.getMarks()<90){
                it.remove();
                repo.delete(st.getId());
            }
        }
        System.out.println("\nAfter removal");
        list.forEach(System.out::println);

        SubjectTeacher t = new SubjectTeacher("T11", "Mr.Sahil Sharma", "Mathematics");
        t.generateReport(list);
    }
}
